---
server:
  port: 8080
spring:
  application:
    name: graphql-user-spring-javaEE

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
    url: "jdbc:h2:mem:testdb"
  h2:
    console:
      enabled: true
      path: "/h2-console"
      settings:
        web-allow-others: true

graphql:
  servlet:
    mapping: "/graphql"
    subscriptions:
      websocket:
        path: "/subscriptions"
    context-setting: per_query_with_instrumentation
    exception-handlers-enabled: true
    cors-enabled: true
    enabled: true
  tools:
    schema-location-pattern: "**/*.graphql"
  playground:
    endpoint: /graphql
    mapping: /playground
    page-title: "user-javaEE-graphQL"
    enabled: true
altair:
  endpoint:
    graphql: /graphql
    subscriptions: /subscriptions
  mapping: /altair
  page-title: "user-javaEE-altair"
  enabled: true
